### ISSUE TITLE
StoryBook

### ISSUE THREAD

**Issue by hin6150** [getsoss/k-project-FE#3]
스토리북 설치 오류

```npx storybook@latest init 
Need to install the following packages:
storybook@8.2.1
Ok to proceed? (y) y

SB_CLI_0001 (FindPackageVersionsError): Unable to find versions of "storybook" using NPM
Reason: SyntaxError: Unexpected non-whitespace character after JSON at position 3
    at QJ.runGetVersions (/Users/hin6150/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/core/dist/common/index.cjs:153538:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doInitiate (/Users/hin6150/.npm/_npx/bc7e1e37fcb46ffc/node_modules/storybook/dist/generate.cjs:157:982)
    at async withTelemetry (/Users/hin6150/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/core/dist/core-server/index.cjs:188662:12)
    at async initiate (/Users/hin6150/.npm/_npx/bc7e1e37fcb46ffc/node_modules/storybook/dist/generate.cjs:191:214) {
  category: 'CLI',
  code: 1,
  data: {
    error: SyntaxError: Unexpected non-whitespace character after JSON at position 3
        at JSON.parse (<anonymous>)
        at QJ.runGetVersions (/Users/hin6150/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/core/dist/common/index.cjs:153533:20)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async doInitiate (/Users/hin6150/.npm/_npx/bc7e1e37fcb46ffc/node_modules/storybook/dist/generate.cjs:157:982)
        at async withTelemetry (/Users/hin6150/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/core/dist/core-server/index.cjs:188662:12)
        at async initiate (/Users/hin6150/.npm/_npx/bc7e1e37fcb46ffc/node_modules/storybook/dist/generate.cjs:191:214),
    packageManager: 'NPM',
    packageName: 'storybook'
  },
  documentation: false,
  fromStorybook: true
}```

**Comment by hin6150** [comment]
@seowooda Solved
